# Generated by Django 3.2.6 on 2021-08-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clevercards_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
    ]
