# Generated by Django 3.2.6 on 2021-08-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clevercards_app', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='topic',
            new_name='subject',
        ),
    ]
